apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-app
  namespace: dev
spec:
  replicas: 1 # Active Pods for the current RS
  revisionHistoryLimit: 2 # Retain two old ReplicaSets in history
  selector:
    matchLabels:
      app: playground
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
        - name: playground
          image: wil42/playground:v2
          ports:
            - containerPort: 8080
