apiVersion: v1
kind: Service
metadata:
  name: husahuc-service
  namespace: dev
spec:
  selector:
    app: husahucapp # Match labels in your Deployment or Pods
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
