apiVersion: v1
kind: Service
metadata:
  name: husahuc-service
  namespace: dev
spec:
  selector:
    app: playground
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 8888
  type: NodePort
